Lv\ShopBundle\Entity\Business:
  type: entity
  table: business
  fields:
    businessId:
      id: true
      type: bigint
      column: business_id
      generator:
        strategy: IDENTITY
    businessName:
      type: text
      nullable: false
      column: business_name
    sortNo:
      type: integer
      nullable: false
      column: sort_no
    updated:
      type: datetime
      nullable: false
      options: ##Unknown attribute type##
      options:
        default: CURRENT_TIMESTAMP
    created:
      type: datetime
      nullable: false
      options: ##Unknown attribute type##
      options:
        default: CURRENT_TIMESTAMP
    deleted:
      type: datetime
      nullable: true
