Lv\ShopBundle\Entity\Shop:
  repositoryClass: Lv\ShopBundle\Repository\ShopRepository
  type: entity
  table: shop
  fields:
    id:
      id: true
      type: bigint
      column: shop_id
      generator:
        strategy: IDENTITY
    shopAccountId:
      type: bigint
      nullable: false
      column: shop_account_id
    businessId:
      type: bigint
      nullable: false
      column: business_id
    companyName:
      type: text
      nullable: false
      column: company_name
    prefectureId:
      type: bigint
      nullable: false
      column: prefecture_id
    municipalityCd:
      type: string
      length: 8
      nullable: true
      column: municipality_cd
    address:
      type: text
      nullable: false
      column: address
    buildingName:
      type: text
      nullable: true
      column: building_name
    mail:
      type: text
      nullable: true
      column: mail
    tel:
      type: text
      nullable: true
      column: tel
    capacity:
      type: integer
      nullable: true
      column: capacity
    updated:
      type: datetime
      nullable: false
      options: ##Unknown attribute type##
      options:
        default: CURRENT_TIMESTAMP
    created:
      type: datetime
      nullable: false
      options: ##Unknown attribute type##
      options:
        default: CURRENT_TIMESTAMP
    deleted:
      type: datetime
      nullable: true
  manyToOne:
    shopAccount:
      targetEntity: Lv\ShopaccountBundle\Entity\ShopAccount
      orphanRemoval: false
      joinColumns:
        shop_account_id:
          referencedColumnName: shop_account_id
    business:
      targetEntity: Lv\PlatformBundle\Entity\Business
      orphanRemoval: false
      joinColumns:
        business_id:
          referencedColumnName: business_id
    prefecture:
      targetEntity: Lv\PlatformBundle\Entity\Prefecture
      orphanRemoval: false
      joinColumns:
        prefecture_id:
          referencedColumnName: prefecture_id

  #lifecycleCallbacks: { }
  #lifecycleCallbacks:
  #  prePersist: [ setCreatedValue, setUpdatedValue ]
  #  preUpdate: [ setUpdatedValue ]