lv_prefecture:
    pattern:  /
    defaults: { _controller: "LvPlatformBundle:Prefecture:index" }

lv_prefecture_show:
    pattern:  /{id}/show
    defaults: { _controller: "LvPlatformBundle:Prefecture:show" }

lv_prefecture_new:
    pattern:  /new
    defaults: { _controller: "LvPlatformBundle:Prefecture:new" }

lv_prefecture_create:
    pattern:  /create
    defaults: { _controller: "LvPlatformBundle:Prefecture:create" }
    requirements: { _method: post }

lv_prefecture_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "LvPlatformBundle:Prefecture:edit" }

lv_prefecture_update:
    pattern:  /{id}/update
    defaults: { _controller: "LvPlatformBundle:Prefecture:update" }
    requirements: { _method: post }

lv_prefecture_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "LvPlatformBundle:Prefecture:delete" }
    requirements: { _method: post }
