parameters:
    database_driver: pdo_pgsql
    database_host: 127.0.0.1
    database_port: null
    database_name: testdb
    database_user: atago
    database_password: atago
    mailer_transport: smtp
    mailer_host: 127.0.0.1
    mailer_user: null
    mailer_password: null
    locale: ja
    secret: 3cea46f17584560002d4457bec2a1ae4617e5b20
    database_path: null
