<?php

namespace Lv\PlatformBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * MunicipalityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MunicipalityRepository extends EntityRepository
{
}
