lv_shop_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: LvPlatformBundle:Default:index }

lv_shop_shop:
  resource: "@LvShopBundle/Resources/config/routing/shop.yml"
  prefix:   /shop
