# src\Lv\ShopBundle\Resources\config\validation.yml
Lv\ShopBundle\Entity\Shop:
  properties:
    id:
      - NotBlank: ~
    shopAccountId:
      - Valid: ~
    businessId:
      - Valid: ~
    companyName:
      - NotBlank: ~
    prefectureId:
      - Valid: ~
    address:
      - NotBlank: ~
    mail:
      - Email:
          #Symfony\Resources\translations で定義.
          #message: The email "{{ value }}" is not a valid email.
          checkMX: true
