parameters:
#    lv_shopaccount.example.class: Lv\ShopaccountBundle\Example

services:
#    lv_shopaccount.example:
#        class: %lv_shopaccount.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
