Lv\PlatformBundle\Entity\Prefecture:
  repositoryClass: Lv\PlatformBundle\Repository\PrefectureRepository
  type: entity
  table: prefecture
  fields:
    id:
      id: true
      type: bigint
      column: prefecture_id
      generator:
        strategy: IDENTITY
    prefectureName:
      type: text
      nullable: false
      column: prefecture_name
    areaId:
      type: integer
      nullable: false
      column: area_id
    areaSort:
      type: integer
      nullable: false
      column: area_sort
    updated:
      type: datetime
      nullable: false
      options: ##Unknown attribute type##
      options:
        default: CURRENT_TIMESTAMP
    created:
      type: datetime
      nullable: false
      options: ##Unknown attribute type##
      options:
        default: CURRENT_TIMESTAMP
    deleted:
      type: datetime
      nullable: true
  manyToOne:
    area:
      targetEntity: Lv\PlatformBundle\Entity\Area
      orphanRemoval: false
      joinColumns:
        area_id:
          referencedColumnName: area_id
