parameters:
#    lv_platform.example.class: Lv\PlatformBundle\Example

services:
#    lv_platform.example:
#        class: %lv_platform.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
