parameters:
#    lv_test.validator.validaddress.class: Lv\TestBundle\Validator\ValidAddressValidator
#    lv_shop.example.class: Lv\ShopBundle\Example

services:
    lv_test.validator.validaddress:
        #class: %lv_test.validator.validaddress.class%
        class: Lv\TestBundle\Validator\ValidAddressValidator
        arguments:
            entityManager: "@doctrine.orm.entity_manager"
        tags:
            - { name: validator.constraint_validator, alias: lv_test_address_validator }

#    lv_shop.example:
#        class: %lv_shop.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]