parameters:
#    lv_test.example.class: Lv\TestBundle\Example

services:
#    lv_test.example:
#        class: %lv_test.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]

    validator.unique.your_validator_name:
        class: Lv\Platform\Validator\Constraints\ContainsAlphanumericValidator
        tags:
            - { name: validator.constraint_validator, alias: ContainsAlphanumericValidator }