# src/Lv/TestBundle/Resources/config/validation.yml
Lv\TestBundle\Entity\Member:
    properties:
        name_eng:
            - NotBlank: ~
            - Lv\PlatformBundle\Validator\Constraints\ContainsAlphanumeric: ~
        address:
            - NotBlank: ~
            - Lv\TestBundle\Validator\ValidAddress: ~
